### ISSUE TITLE
源码不能识别 result为空

### ISSUE THREAD

**Issue by ltto** [pjialin/12306-ocr#12]
![image](https://user-images.githubusercontent.com/24884691/71443425-cfc14d00-2745-11ea-9d5d-e10f3604adbb.png)
![tkcode](https://user-images.githubusercontent.com/24884691/71443440-dea7ff80-2745-11ea-98cf-b347f0bd2a2f.png)

**Comment by ltto** [comment]
docker run -d -p 8000:8000 --rm pjialin/12306-ocr

**Comment by ltto** [comment]
解决了 去掉data:image/png;base64,

**Comment by ShengZhang2016** [comment]
同学您好，这个图片的地址是这个对吗？https://user-images.githubusercontent.com/24884691/71443440-dea7ff80-2745-11ea-98cf-b347f0bd2a2f.png
我也得到的 result 为空。。不知道是不是地址不对，希望能看到
