### ISSUE TITLE
运行提示POST / HTTP/1.1" 404

### ISSUE THREAD

**Issue by IronXiao** [pjialin/12306-ocr#13]
运行一直提示POST / HTTP/1.1" 404
`Using TensorFlow backend.
 * Serving Flask app "web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:63323/ (Press CTRL+C to quit)
127.0.0.1 - - [27/Dec/2019 10:51:39] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:51:44] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:51:54] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:51:59] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:04] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:09] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:14] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:20] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:25] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:30] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:35] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:40] "POST / HTTP/1.1" 404 -
127.0.0.1 - - [27/Dec/2019 10:52:46] "POST / HTTP/1.1" 404 -`

py12306 也一直提示打码失败：
`正在下载验证码...
打码失败: 错误原因 从免费打码获取结果失败
5 秒后重新获取验证码
正在下载验证码...
打码失败: 错误原因 从免费打码获取结果失败
5 秒后重新获取验证码`

**Comment by pjialin** [comment]
检查地址是否正确。应该是 `/check` 结尾
